services:
  shop-swap:
    build: 
      context: Backend
    mem_limit: 512m
    ports:
      - "8443:8443"
    environment:
      DB_URL: jdbc:mysql://shop_swap:3306/shop-swap?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      shop_swap:
        condition: service_healthy

  shop_swap:
    image: mysql:8.4.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: shop_swap
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
